import Link from "next/link";
import { notFound } from "next/navigation";
import { requireViewer } from "@/server/auth/guard";
import { getTripForOwner } from "@/server/domains/trips/service";
import { loadCandidates } from "@/server/domains/trips/service";
import { applyTripModificationAction } from "@/server/actions/user";
import { Card } from "@/components/ui/primitives";
import { formatINR, formatDate, minutesToTime, formatMinutes } from "@/lib/utils";

export const dynamic = "force-dynamic";

const ITEM_ICONS: Record<string, string> = {
  ATTRACTION: "📍",
  MEAL: "🍽️",
  TRAVEL: "🚌",
  CHECKIN: "🏨",
  REST: "☕",
  ACTIVITY: "🏄",
  EVENT: "🎉",
};

export default async function TripDetailPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ error?: string }>;
}) {
  const { id } = await params;
  const sp = await searchParams;
  const viewer = await requireViewer();

  let trip: Awaited<ReturnType<typeof getTripForOwner>>;
  try {
    trip = await getTripForOwner(id, viewer.id);
  } catch {
    notFound();
  }

  const candidates = await loadCandidates().catch(() => []);
  const topCandidates = candidates.slice(0, 40);

  return (
    <div>
      <nav aria-label="Breadcrumb" className="text-sm text-ink-900/60">
        <Link href="/dashboard/trips" className="hover:text-brand-700">My trips</Link> <span aria-hidden>/</span> {trip.title}
      </nav>

      <header className="mt-2 flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl font-semibold">{trip.title}</h1>
          <p className="mt-1 text-sm text-ink-900/70">
            From {trip.originName} · {formatDate(trip.startDate)} – {formatDate(trip.endDate)} · {trip.adults} adult(s)
            {trip.children > 0 ? `, ${trip.children} child(ren)` : ""}
            {trip.seniors > 0 ? `, ${trip.seniors} senior(s)` : ""}
          </p>
          <p className="mt-1 text-sm">
            Estimated cost: <strong>{trip.estimatedCost ? formatINR(trip.estimatedCost) : "—"}</strong>
            {trip.aiExplanation ? <span className="text-ink-900/60"> · generated by the Sanchari engine</span> : null}
          </p>
        </div>
        {trip.shareToken ? (
          <Link href={`/share/${trip.shareToken}`} className="rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold hover:border-brand-300">
            🔗 Public share view
          </Link>
        ) : null}
      </header>

      {sp.error ? <p role="alert" className="mt-4 rounded-xl bg-spice-50 px-4 py-3 text-sm text-spice-700">{sp.error}</p> : null}

      {trip.days_.length === 0 ? (
        <Card className="mt-6 p-8 text-center text-sm text-ink-900/60">This trip has no itinerary days.</Card>
      ) : null}

      <div className="mt-8 space-y-8">
        {trip.days_.map((day) => (
          <section key={day.id} aria-labelledby={`day-${day.dayNumber}`}>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h2 id={`day-${day.dayNumber}`} className="font-display text-2xl font-semibold">
                Day {day.dayNumber}
                {day.clusterName ? <span className="ml-2 text-base font-normal text-ink-900/60">{day.clusterName}</span> : null}
              </h2>
              <div className="flex flex-wrap gap-2 text-xs font-semibold">
                <form action={applyTripModificationAction}>
                  <input type="hidden" name="tripId" value={trip.id} />
                  <input type="hidden" name="op" value="shift" />
                  <input type="hidden" name="dayNumber" value={day.dayNumber} />
                  <input type="hidden" name="delta" value={30} />
                  <button className="rounded-lg border border-sand-200 bg-surface px-3 py-1.5 hover:border-brand-300">+30 min late</button>
                </form>
                <form action={applyTripModificationAction}>
                  <input type="hidden" name="tripId" value={trip.id} />
                  <input type="hidden" name="op" value="shift" />
                  <input type="hidden" name="dayNumber" value={day.dayNumber} />
                  <input type="hidden" name="delta" value={-30} />
                  <button className="rounded-lg border border-sand-200 bg-surface px-3 py-1.5 hover:border-brand-300">−30 min early</button>
                </form>
                <form action={applyTripModificationAction}>
                  <input type="hidden" name="tripId" value={trip.id} />
                  <input type="hidden" name="op" value="weather" />
                  <input type="hidden" name="dayNumber" value={day.dayNumber} />
                  <button className="rounded-lg border border-coast-500 bg-coast-100 px-3 py-1.5 text-coast-700 hover:bg-coast-500 hover:text-white">🌧️ Rain plan</button>
                </form>
              </div>
            </div>

            <ol className="mt-4 space-y-2.5">
              {day.items.map((item) => (
                <li key={item.id}>
                  <Card className={`flex items-start gap-4 p-4 ${item.locked ? "border-brand-300 bg-brand-50/40" : ""}`}>
                    <div className="w-24 shrink-0 text-right">
                      <p className="text-sm font-bold tabular-nums">{minutesToTime(item.startTimeMin)}</p>
                      <p className="text-[11px] text-ink-900/50">– {minutesToTime(item.endTimeMin)}</p>
                    </div>
                    <span aria-hidden className="grid size-9 shrink-0 place-items-center rounded-full bg-sand-100 text-base">
                      {ITEM_ICONS[item.itemType] ?? "•"}
                    </span>
                    <div className="min-w-0 flex-1">
                      <p className="flex flex-wrap items-center gap-2 font-semibold">
                        {item.title}
                        {item.locked ? <span title="Booked/locked — never moved by rescheduling" className="rounded bg-brand-600 px-1.5 py-0.5 text-[10px] font-bold uppercase text-white">Locked</span> : null}
                        {item.weatherSensitive ? <span title="Weather-sensitive outdoor stop" className="text-xs">🌦️</span> : null}
                      </p>
                      {item.placeName ? <p className="text-xs text-ink-900/60">{item.placeName}{item.travelFromPrevMinutes > 0 ? ` · ${formatMinutes(item.travelFromPrevMinutes)} travel` : ""}</p> : null}
                      {item.reason ? <p className="mt-1 line-clamp-2 text-xs italic text-ink-900/60">💡 {item.reason}</p> : null}
                      {item.estimatedCostPerPerson > 0 ? <p className="mt-1 text-xs font-medium text-spice-700">{formatINR(item.estimatedCostPerPerson)} / person</p> : null}
                    </div>
                    {!item.locked && item.itemType !== "MEAL" ? (
                      <form action={applyTripModificationAction} className="shrink-0">
                        <input type="hidden" name="tripId" value={trip.id} />
                        <input type="hidden" name="op" value="remove" />
                        <input type="hidden" name="dayNumber" value={day.dayNumber} />
                        <input type="hidden" name="match" value={item.title} />
                        <button className="rounded-lg px-2 py-1.5 text-xs font-semibold text-danger hover:bg-danger/10" title={`Remove ${item.title}`}>
                          Skip
                        </button>
                      </form>
                    ) : null}
                  </Card>
                </li>
              ))}
            </ol>

            <details className="mt-3">
              <summary className="cursor-pointer text-sm font-semibold text-brand-700 hover:text-brand-800">+ Add a stop to this day</summary>
              <form action={applyTripModificationAction} className="mt-2 flex flex-wrap gap-2">
                <input type="hidden" name="tripId" value={trip.id} />
                <input type="hidden" name="op" value="add" />
                <input type="hidden" name="dayNumber" value={day.dayNumber} />
                <select name="slug" required className="min-w-0 flex-1 rounded-xl border border-sand-200 bg-surface px-3 py-2 text-sm sm:max-w-md">
                  <option value="">Choose a place…</option>
                  {topCandidates.map((c) => (
                    <option key={c.slug} value={c.slug}>
                      {c.name} — {c.districtName} ({c.type.toLowerCase().replace(/_/g, " ")})
                    </option>
                  ))}
                </select>
                <button className="rounded-xl bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-700">Add stop</button>
              </form>
              <p className="mt-1 text-xs text-ink-900/50">The engine finds the least disruptive slot and reflows the rest of the day.</p>
            </details>
          </section>
        ))}
      </div>

      {trip.bookings.length > 0 ? (
        <section className="mt-10" aria-labelledby="trip-bookings">
          <h2 id="trip-bookings" className="font-display text-2xl font-semibold">Linked bookings</h2>
          <ul className="mt-3 divide-y divide-sand-100 rounded-2xl border border-sand-200 bg-surface text-sm">
            {trip.bookings.map((b) => (
              <li key={b.id} className="flex items-center justify-between px-5 py-3">
                <span>
                  <Link href="/dashboard/bookings" className="font-mono font-semibold hover:text-brand-700">{b.reference}</Link> · {b.titleSnapshot}
                </span>
                <span className="font-semibold capitalize">{b.status.toLowerCase().replace(/_/g, " ")}</span>
              </li>
            ))}
          </ul>
        </section>
      ) : null}
    </div>
  );
}
